[env:esp32s3-supermini]
platform            = espressif32
board               = esp32-s3-supermini
framework           = arduino
monitor_speed       = 115200
upload_speed        = 921600

; ESP32-S3 Super Mini uses native USB (USB CDC) for serial
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

; Reference shared libraries in the monorepo
lib_extra_dirs = ../shared
